micronaut:
  application:
    name: micronautResilience
  security:
    authentication: bearer
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        generator:
          refresh-token:
            secret: useSomeSecureStringHereThatIsAtLeast256BitsForRefresh
        signatures:
          secret:
            generator:
              secret: useSomeSecureStringHereThatIsAtLeast256Bits
endpoints:
  info:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: false
  health:
    enabled: true
    sensitive: false
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/todos-db?retryWrites=false
netty:
  default:
    allocator:
      max-order: 3
